---
name: Ansible role testing
'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          path: 'miarec.loki'

      - name: Run yamllint
        uses: karancode/yamllint-github-action@master
        with:
          # yamllint_file_or_dir: 'ansible/roles/loki'
          yamllint_strict: false
          yamllint_comment: false
          # yamllint_config_filepath: 'ansible/roles/loki/.yamlint'

      - name: Install test dependencies
        run: |
          pip3 install ansible-lint
          cd miarec.loki
          ansible-lint

      # - name: Run ansible-lint
      #   uses: ansible/ansible-lint-action@main
        # with:
        #   override-deps: ansible-lint==5.3.2
        #   # https://github.com/ansible-community/ansible-lint/issues/1795

  test:
    name: molecule
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos7
          - centos8
          - ubuntu2004
          - ubuntu2204

    steps:
      - name: Check out the Repository
        uses: actions/checkout@v2
        # with:
        #   path: 'miarec.loki'

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: pip3 install -r test-requirements.txt

      - name: Run molecule tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
